/** BotFlow auth layout styling — structure only, brand purple colors. */
export const clerkAuthAppearance = {
  variables: {
    colorPrimary: "#7C3AED",
    colorDanger: "var(--destructive)",
    colorSuccess: "#7C3AED",
    colorWarning: "#fbbf24",
    colorNeutral: "var(--muted-foreground)",
    colorText: "var(--foreground)",
    colorTextSecondary: "var(--muted-foreground)",
    colorBackground: "var(--background)",
    colorInputBackground: "var(--background)",
    colorInputText: "var(--foreground)",
    borderRadius: "0.75rem",
    fontFamily: "var(--font-geist-sans), system-ui, sans-serif",
    spacingUnit: "1rem",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full shadow-none",
    card: "auth-clerk-card w-full bg-card border border-border/60 rounded-2xl shadow-xl",
    header: "gap-2",
    headerTitle: "text-foreground text-[1.65rem] font-bold tracking-tight",
    headerSubtitle: "text-muted-foreground text-sm",
    socialButtonsBlockButton:
      "bg-background border border-border/60 text-foreground hover:bg-muted/50 hover:border-primary/30 transition-colors",
    socialButtonsBlockButtonText: "text-foreground font-medium",
    formButtonPrimary:
      "auth-clerk-primary bg-primary text-primary-foreground font-semibold hover:bg-primary/90 border-0 normal-case text-sm",
    formFieldInput:
      "bg-background border-border/60 text-foreground placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20",
    formFieldLabel: "text-foreground text-sm font-medium",
    formFieldLabelRow: "items-center",
    footerActionLink: "text-primary hover:text-primary/90 font-medium",
    identityPreviewEditButton: "text-primary",
    identityPreviewText: "text-foreground",
    dividerLine: "bg-border",
    dividerText: "text-muted-foreground text-xs uppercase",
    formFieldInputShowPasswordButton: "text-muted-foreground hover:text-foreground",
    footer: "hidden",
    footerAction: "hidden",
    navbar: "hidden",
    logoBox: "hidden",
    alertText: "text-sm",
    otpCodeFieldInput: "border-border/60 bg-background text-foreground",
    formResendCodeLink: "text-primary",
    backLink: "text-primary hover:text-primary/90",
    formFieldAction: "text-primary hover:text-primary/90 text-sm font-medium",
    alternativeMethodsBlockButton:
      "border-border/60 bg-background text-foreground hover:border-primary/30",
    badge: "bg-primary/10 text-primary border-primary/20",
  },
} as const;
