/** BotFlow auth — AdSkull layout structure, brand purple colors. */
export const clerkAuthAppearance = {
  variables: {
    colorPrimary: "#7C3AED",
    colorDanger: "var(--destructive)",
    colorSuccess: "#7C3AED",
    colorWarning: "#fbbf24",
    colorNeutral: "var(--muted-foreground)",
    colorText: "var(--foreground)",
    colorTextSecondary: "var(--muted-foreground)",
    colorBackground: "transparent",
    colorInputBackground: "var(--background)",
    colorInputText: "var(--foreground)",
    borderRadius: "0.75rem",
    fontFamily: "var(--font-geist-sans), system-ui, sans-serif",
    spacingUnit: "0.875rem",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full shadow-none",
    card: "w-full bg-transparent border-0 shadow-none p-0 gap-5",
    header: "gap-1 text-center sm:text-center",
    headerTitle: "text-foreground text-2xl font-bold tracking-tight",
    headerSubtitle: "text-muted-foreground text-sm font-normal",
    socialButtonsBlockButton:
      "h-11 bg-background border border-border/60 text-foreground hover:bg-muted/40 hover:border-primary/25 transition-colors",
    socialButtonsBlockButtonText: "text-foreground font-medium",
    formButtonPrimary:
      "auth-clerk-primary h-11 w-full bg-primary text-primary-foreground font-semibold hover:bg-primary/90 border-0 normal-case text-sm",
    formFieldInput:
      "h-11 bg-background border-border/60 text-foreground placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20",
    formFieldLabel: "text-foreground text-sm font-medium",
    formFieldLabelRow: "items-center justify-between w-full",
    formFieldRow: "gap-2",
    footerActionLink: "text-primary hover:text-primary/90 font-medium",
    identityPreviewEditButton: "text-primary",
    identityPreviewText: "text-foreground",
    dividerRow: "my-2",
    dividerLine: "bg-border",
    dividerText: "text-muted-foreground text-xs lowercase",
    formFieldInputShowPasswordButton: "text-muted-foreground hover:text-foreground",
    footer: "pt-2",
    footerAction: "hidden",
    footerPages: "text-center",
    footerPagesLink: "text-primary hover:text-primary/90 font-medium",
    navbar: "hidden",
    logoBox: "hidden",
    alertText: "text-sm",
    otpCodeFieldInput: "border-border/60 bg-background text-foreground",
    formResendCodeLink: "text-primary",
    backLink: "text-primary hover:text-primary/90",
    formFieldAction: "text-primary hover:text-primary/90 text-sm font-medium",
    alternativeMethodsBlockButton:
      "border-border/60 bg-background text-foreground hover:border-primary/25",
    badge: "bg-primary/10 text-primary border-primary/20",
    main: "gap-5",
    form: "gap-4",
  },
} as const;
